// react-app/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import {TodoComponent} from './components/Todo.jsx';
import './App.css';
import app from './services/service.js';

export class App extends Component {
    constructor(props){
      // on loading set up props with all current todo
      super(props);
      this.state = {text:''};
      // setting up props.todos to todoService
    }

  addTodo(){
    // function to add todo to the list.

    var title = this.state.text;
    // create instance of todo
    app.TodoStore.addTodo(title);
  }

  removeTodo(){
    // removing todo elemeent and addition
  }

  render() {
    return (
      <section>
      <header className="header">
      	<h1>Todo MVC angular</h1>
      		<form id="todo-form">
      			<input id="new-todo" onChange={this.addTodo} placeholder="What needs to be done?" value={this.state.text} autofocus="" />
      		</form>
      </header>
      <section id="main">
      	<input className="toggle-all" type="checkbox"/>
        <ul>
          <TodoComponent todos = {this.props.models.todos} />
        </ul>
      </section>
      </section>

    );
  }
}


export default App;

// angular2/client/src/app/components/appComponent/app.component.ts
import { Component } from '@angular/core';
import {TodoStoreService} from '../../service/TodoStore/todo-store.service';
import { Todo } from '../../service/todo';

@Component({
  selector: 'app-root',
  templateUrl: './components/appComponent/app.component.html',
  styleUrls: ['./components/appComponent/app.component.css']

})
export class AppComponent {
  todoStore: TodoStoreService;
  newTodoText:string;
  todo:Todo

  constructor(todoStore: TodoStoreService){
    this.todoStore=todoStore;
  }

  addTodo(){
    // this makes a request to add the todo to the list.
    this.todo=new Todo(this.newTodoText);
    this.todo.completed=false;
    //sending this todo via the service to update store.
    this.todoStore.add(this.todo);
  }

  editTodo(todo:Todo){
    todo.editing=true;
  }

  stopEditing(todo: Todo, editedTitle: string) {
		todo.title = editedTitle;
		todo.editing = false;
	}

	cancelEditingTodo(todo: Todo) {
		todo.editing = false;
	}

	updateEditingTodo(todo: Todo, editedTitle: string) {
		editedTitle = editedTitle.trim();
		todo.editing = false;

		if (editedTitle.length === 0) {
			return this.todoStore.delete(todo);
		}

		todo.title = editedTitle;
	}

  remove(todo: Todo){
    this.todoStore.delete(todo);
  }

  removeCompleted(){
    //removing all todo with completed set to True
    this.todoStore.removeCompleted();
  }


}

<section class="todoapp">
	<header class="header">
		<h1>Todo Angular 2 </h1>
		<input class="new-todo" placeholder="What needs to be done?" autofocus="" [(ngModel)]="newTodoText" (keyup.enter)="addTodo()">
	</header>

	<!-- the section listening to the list. of todos -->
	<section class="main" *ngIf="todoStore.todos.length > 0">
		<input class="toggle-all" type="checkbox" *ngIf="todoStore.todos.length" #toggleall [checked]="todoStore.allCompleted()" >
		<!-- the service has a class allCompleted() -->

		<ul class="todo-list">
			<li *ngFor="let todo of todoStore.todos" [class.completed]="todo.completed" [class.editing]="todo.editing">

				<div class="view">
					<input class="toggle" type="checkbox" (click)="toggleCompletion(todo)" [checked]="todo.completed">
					<label (dblclick)="editTodo(todo)">{{todo.title}}</label>
					<button class="destroy" (click)="remove(todo)"></button>
				</div>

				<input class="edit" *ngIf="todo.editing" [value]="todo.title" #editedtodo (blur)="stopEditing(todo, editedtodo.value)" (keyup.enter)="updateEditingTodo(todo, editedtodo.value)" (keyup.escape)="cancelEditingTodo(todo)">

			</li>
		</ul>
	</section>
	<footer class="footer" *ngIf="todoStore.todos.length > 0">
		<span class="todo-count"><strong>{{todoStore.getRemaining().length}}</strong> {{todoStore.getRemaining().length == 1 ? 'item' : 'items'}} left</span>
		<button class="clear-completed" *ngIf="todoStore.getCompleted().length > 0" (click)="removeCompleted()">Clear completed</button>
	</footer>
</section>
